//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/InputSystem/TouchControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TouchControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TouchControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""TouchControls"",
    ""maps"": [
        {
            ""name"": ""Drawing"",
            ""id"": ""329dc8d5-f979-4dfd-82ee-739a01533768"",
            ""actions"": [
                {
                    ""name"": ""Tuch"",
                    ""type"": ""Button"",
                    ""id"": ""344c57cb-974d-40a4-a468-2a98b7db8f50"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b79e6005-b772-4b03-b4ea-c16f40807dd1"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tuch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Drawing
        m_Drawing = asset.FindActionMap("Drawing", throwIfNotFound: true);
        m_Drawing_Tuch = m_Drawing.FindAction("Tuch", throwIfNotFound: true);
    }

    ~@TouchControls()
    {
        UnityEngine.Debug.Assert(!m_Drawing.enabled, "This will cause a leak and performance issues, TouchControls.Drawing.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Drawing
    private readonly InputActionMap m_Drawing;
    private List<IDrawingActions> m_DrawingActionsCallbackInterfaces = new List<IDrawingActions>();
    private readonly InputAction m_Drawing_Tuch;
    public struct DrawingActions
    {
        private @TouchControls m_Wrapper;
        public DrawingActions(@TouchControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Tuch => m_Wrapper.m_Drawing_Tuch;
        public InputActionMap Get() { return m_Wrapper.m_Drawing; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DrawingActions set) { return set.Get(); }
        public void AddCallbacks(IDrawingActions instance)
        {
            if (instance == null || m_Wrapper.m_DrawingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DrawingActionsCallbackInterfaces.Add(instance);
            @Tuch.started += instance.OnTuch;
            @Tuch.performed += instance.OnTuch;
            @Tuch.canceled += instance.OnTuch;
        }

        private void UnregisterCallbacks(IDrawingActions instance)
        {
            @Tuch.started -= instance.OnTuch;
            @Tuch.performed -= instance.OnTuch;
            @Tuch.canceled -= instance.OnTuch;
        }

        public void RemoveCallbacks(IDrawingActions instance)
        {
            if (m_Wrapper.m_DrawingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDrawingActions instance)
        {
            foreach (var item in m_Wrapper.m_DrawingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DrawingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DrawingActions @Drawing => new DrawingActions(this);
    public interface IDrawingActions
    {
        void OnTuch(InputAction.CallbackContext context);
    }
}
